[tool.poetry]
name = "coursework_3"
version = "0.1.0"
description = ""
authors = ["Maxim Abavi <afghan1363@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
